name: Docker Image CI

on:
  push:
    branches: [ action_docker ]
  pull_request:
    branches: [ action_docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build using the Docker-compose.yml
      run: cd docker && docker-compose build docker-distro 
    
    - name: run the built image
      run: docker run --rm -i trial:latest bash -c "pwd;ls; /venv/bin/pip list; /venv/bin/python3 test.py"
      

    - name: Build the Docker image
      run: docker build ./docker --file Dockerfile --tag my-image-name:$(date +%s)
